workflows:
  ios-workflow:
    name: iOS Build & Upload to App Store (Flutter)
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app-store-credentials3
        - firebase-secrets
      vars:
        CM_APPLE_DEV_TEAM_ID: "6573BLNWHL"
        APP_STORE_CONNECT_TEAM_ID: "6573BLNWHL"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zoomubik.app
    scripts:
      - name: Restore GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Pod Install
        script: |
          cd ios && pod install --repo-update
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Bump build number
        script: |
          LATEST=$(app-store-connect get-latest-testflight-build-number 6760907092)
          agvtool new-version -all $(($LATEST + 1))
      - name: Build Flutter
        script: |
          flutter build ios --release --no-codesign
      - name: Build IPA
        script: |
          cd ios
          xcodebuild -
